---
abstract: 'Request parameter condition plugin'
author:
  - 'Brian Medley <freesoftware@bmedley.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-ParamCondition
requires:
  Mojolicious: 0
version: 0.003
